# Generated by Django 5.2.17 on 2026-09-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_campus_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_raw', models.CharField(help_text='What was actually scanned/submitted.', max_length=120)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('session_key', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='floor_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Hide draft locations from the visitor app.'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_scannable',
            field=models.BooleanField(default=True, help_text='Whether a QR sticker exists for this location.'),
        ),
        migrations.AddField(
            model_name='location',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Admin', 'Admin'), ('Entrance', 'Entrance'), ('Facility', 'Facility'), ('Food', 'Food'), ('Sports', 'Sports'), ('Parking', 'Parking'), ('Hostel', 'Hostel'), ('Medical', 'Medical'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['category'], name='campus_loca_categor_ee2eb3_idx'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='campus.location'),
        ),
        migrations.AddField(
            model_name='tourstop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_stops', to='campus.location'),
        ),
        migrations.AddField(
            model_name='tourstop',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='campus.tour'),
        ),
        migrations.AddConstraint(
            model_name='tourstop',
            constraint=models.UniqueConstraint(fields=('tour', 'order'), name='unique_tour_stop_order'),
        ),
    ]
